#!/bin/bash
BASE=$PWD
source /jet/packages/oneapi/v2023.2.0/compiler/2023.2.1/env/vars.sh

MPI=impi-2021.10.0
MPI=hpcx-2.18
if [[ "$MPI" =~ ^impi ]]; then
        source /jet/packages/oneapi/v2023.2.0//mpi/2021.10.0/env/vars.sh
        export MPIFC=mpiifort
        export CC=mpiicc
        export FC=$MPIFC
        export WHICHMPI=intelmpi
elif [[ "$MPI" =~ ^hpcx ]]; then
        module use $HOME/tools/$MPI/modulefiles
        module load hpcx
        export OMPI_CC=icc
        export OMPI_CXX=icpc
        export OMPI_FC=ifort
        export OMPI_F90=ifort
        export MPIFC=mpif90
        export CC=mpicc
        export FC=mpif90
        export WHICHMPI=openmpi
fi
cd src
export MPI
make clean
make

cd $BASE/bin
mv Conquest Conquest-$MPI